### ISSUE TITLE
Storing null as string in localStorage

### ISSUE THREAD

**Issue by mattfysh** [MyPureCloud/purecloud_api_sdk_javascript#17]
Calling `logout()` sets the local storage key to null, but this is stored as a string by the browser. When reloading the page, the SDK thinks there is a token since `"null" !== null` ... causes some strange behaviour when calling`login()` later on.

**Comment by mattfysh** [comment]
Additionally, can the `redirectUrl` option be used when calling `logout`?

**Comment by T-Boss** [comment]
Thanks for reporting this. I've logged this bug as API-2271. Should be able to address this soon.

**Comment by mattfysh** [comment]
Thanks @T-Boss - would you prefer if I submitted a pull request instead?

**Comment by KevinGlinski** [comment]
That would be great

**Comment by T-Boss** [comment]
Is this as simple as using `undefined` instead of `null` in [purecloudSession.js:177](https://github.com/MyPureCloud/purecloud_api_sdk_javascript/blob/master/templates/purecloudsession.js#L177) or is there more to it? I haven't had a chance to test it yet.

PRs are definitely welcome, just make sure you don't change anything in the bin/dist directories; that's all generated code.
